version: '3.9'

services:
  frontend:
    build:
      context: ./perfume-front-nextjs
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
